/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    implementation(project(":glass-common"))
    implementation("org.apache.logging.log4j:log4j-core:2.17.2")
    compileOnly("org.spigotmc:spigot-api:1.8-R0.1-SNAPSHOT")
}

description = "glass-spigot"
